stages:
  - build
  - deploy

default:
  image: maven:3.8.5-openjdk-17

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $SSH_SERVER >> ~/.ssh/known_hosts
  script:
    # Обновляем docker-compose.yml в проекте
    - scp docker-compose.yml $SSH_USER@$SSH_SERVER:/home/docker/spc/docker-compose.yml
    # Копируем jar файл
    - scp target/*.jar $SSH_USER@$SSH_SERVER:/home/docker/spc/app
    # Перезапускаем контейнер с новым образом
    - ssh $SSH_USER@$SSH_SERVER "cd /home/docker/spc && docker-compose down && docker-compose up -d --build"
  only:
    - dev
  environment:
    name: production
    url: http://135.181.128.39

