stages:
  - deploy

default:
  image: openjdk:21-slim

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client openjdk21
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p 222 $SSH_SERVER >> ~/.ssh/known_hosts
  script:
    - echo "Compiling the code..."
    - ./gradlew build --stacktrace --info
    - echo "Build completed"
    - scp -P 222 sales-points-counter/build/libs/*.jar $SSH_USER@$SSH_SERVER:/home/docker/spc/app/
    - scp -P 222 docker-compose.yml $SSH_USER@$SSH_SERVER:/home/docker/spc/docker-compose.yml
    - ssh -p 222 $SSH_USER@$SSH_SERVER "cd /home/docker/spc && docker-compose down && docker-compose up -d --build"
  only:
    - main
  environment:
    name: production
    url: http://135.181.128.39  
    ####
