stages:
  - build
  - deploy

default:
  image: openjdk:21-slim

build:
  stage: build
  script:
    - echo "Compiling the code..."

  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $SSH_SERVER >> ~/.ssh/known_hosts
  script:
   
    - scp docker-compose.yml $SSH_USER@$SSH_SERVER:/home/docker/spc/docker-compose.yml
   
    - scp target/*.jar $SSH_USER@$SSH_SERVER:/home/docker/spc/app
  
    - ssh $SSH_USER@$SSH_SERVER "cd /home/docker/spc && docker-compose down && docker-compose up -d --build"
  only:
    - main
  environment:
    name: production
    url: http://135.181.128.39

    ###test
