version: "3.8"
services:
  db:
    container_name: foxminded-activity-database
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /home/docker/spc/db:/var/lib/postgresql/data:rw
    networks:
      - shvirid
      - compose-demo_default

  back:
    container_name: backend
    image: 'openjdk:21-slim'
    restart: always
    ports:
      - "9080:80"
    environment:
      - VIRTUAL_HOST=spc.foxminded.ua
      - REDIRECT=spc.foxminded.ua
      - LETSENCRYPT_HOST=spc.foxminded.ua
      - LETSENCRYPT_EMAIL=admin@foxminded.ua

      - SERVER_PORT=80
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_MAIN_BANNER-MODE=off
      - SPRING_CLOUD_CONFIG_URL=http://config:80
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - PIPEDRIVE_TOKEN=${PIPEDRIVE_TOKEN}
    volumes:
      - /home/docker/spc/app:/app
    command: ['java', '-jar', '/app/sales-points-counter.jar']
    depends_on:
      - db

    networks:
      - shvirid
      - compose-demo_default



networks:
   compose-demo_default:
     external: true
   shvirid: