INSERT INTO manager_points_configuration (owner_id,
                                          manager_points_normative,
                                          manager_points_call_coefficient,
                                          manager_points_test_period_coefficient,
                                          manager_points_bonus_under_3,
                                          manager_points_bonus_equal_3,
                                          manager_points_bonus_over_4,
                                          created_date,
                                          updated_date)
VALUES (13196919,
        55,
        2,
        8,
        0,
        5,
        20,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

INSERT INTO manager_points_configuration (owner_id,
                                          manager_points_normative,
                                          manager_points_call_coefficient,
                                          manager_points_test_period_coefficient,
                                          manager_points_bonus_under_3,
                                          manager_points_bonus_equal_3,
                                          manager_points_bonus_over_4,
                                          created_date,
                                          updated_date)
VALUES (13053732,
        55,
        2,
        8,
        0,
        5,
        20,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

INSERT INTO manager_points_configuration (owner_id,
                                          manager_points_normative,
                                          manager_points_call_coefficient,
                                          manager_points_test_period_coefficient,
                                          manager_points_bonus_under_3,
                                          manager_points_bonus_equal_3,
                                          manager_points_bonus_over_4,
                                          created_date,
                                          updated_date)
VALUES (13196919,
        55,
        2,
        8,
        0,
        5,
        20,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

INSERT INTO manager_points_configuration (owner_id,
                                          manager_points_normative,
                                          manager_points_call_coefficient,
                                          manager_points_test_period_coefficient,
                                          manager_points_bonus_under_3,
                                          manager_points_bonus_equal_3,
                                          manager_points_bonus_over_4,
                                          created_date,
                                          updated_date)
VALUES (13053721,
        55,
        2,
        8,
        0,
        5,
        20,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);