services:
  ngodb:
    container_name: activity
    image: mcr.microsoft.com/mssql/server:2019-CU27-ubuntu-20.04
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd1234!
      - MSSQL_COLLATION=Cyrillic_General_CI_AS
    volumes:
      - /Users/yevheniipiddubnyi/Downloads/shvirid:/db
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "P@ssw0rd1234!" -Q "CREATE DATABASE activity"
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - shvirid

  back:
    container_name: backend
    image: 'openjdk:21-slim'
    restart: always
    ports:
      - "9080:80"
    environment:
      - SERVER_PORT=80
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_MAIN_BANNER-MODE=off
      - SPRING_CLOUD_CONFIG_URI=http://config:80
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      - /Users/yevheniipiddubnyi/Downloads/shvirid/app:/app
    command: ['java', '-jar', '/app/app.jar']
    depends_on:
      ngodb:
        condition: service_healthy
      config:
        condition: service_started
    networks:
      - shvirid

  config:
    container_name: config
    image: 'openjdk:11-jre-slim'
    restart: always
    environment:
      - SERVER_PORT=80
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:///config
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=false
      - SPRING_CLOUD_DISCOVERY_ENABLED=false
    volumes:
      - /Users/yevheniipiddubnyi/Downloads/docker/ngo-cloud-config-server:/app
      - /Users/yevheniipiddubnyi/Downloads/shvirid/configs:/config
    command: [ 'java', '-jar', '/app/app.jar' ]
    networks:
      - shvirid

networks:
  shvirid: